baseurl: '/web/oppcell/'
permalink: pretty
title: 'Jekyll Serif'

port: 4000
host: 127.0.0.1
livereload: true

logo:
  mobile: "images/logo/placementCelllogo.jpg"
  mobile_height: "3rem"
  mobile_width: "5rem"
  desktop: "images/logo/mainlogo.png"
  desktop_height: "80px"
  desktop_width: "300px"

home: 
  limit_services: 6

collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
  
markdown: kramdown

